### ISSUE TITLE
BookControls/Notebook assertion failed in InsertPage(): "invalid notebook imagelist"

### ISSUE THREAD

**Issue by ericfont** [gammasoft71/Examples_wxWidgets#10]
Got this assertion failure when tried to run BookControls/Notebook:

![2021-09-15_20-19](https://user-images.githubusercontent.com/6502474/133529747-b4d0efcb-0199-4906-9917-8866641b741c.png)

**Comment by gammasoft71** [comment]
Fixed https://github.com/gammasoft71/Examples_wxWidgets/commit/4d6d014033885391bf9aa14963bc94b4aabfe7f9
