### ISSUE TITLE
Can't build on Windows 10 (MSVC) if wxwidgets installed by vcpkg

### ISSUE THREAD

**Issue by slavroman** [gammasoft71/Examples_wxWidgets#19]
Hello! I'm try to compile your examples according your instruction from `README.md`

> mkdir build && cd build
cmake ..
start wxWidgetsExamples.sln

When I type `cmake ..` in build directory I've receive error, please see screen bottom.

![2024-07-07 233413](https://github.com/gammasoft71/Examples_wxWidgets/assets/34276362/54ef455c-efa2-4de1-af44-298bfb013ad1)

P.S.>Have installed wxwidgets dynamic and static x86 & x64 through `vcpkg`

> wxwidgets:x64-windows                             3.2.5#3
wxwidgets:x64-windows-static                      3.2.5#3
wxwidgets:x86-windows                             3.2.5#3
wxwidgets:x86-windows-static                      3.2.5#3

Will appreciate any help, thanks!

**Comment by gammasoft71** [comment]
Hello,

First of all thank you for interest in my project.

There is a simple way to do it.

```bash
set CMAKE_TOOLCHAIN_FILE=<vcpkg_root>/scripts/buildsystems/vcpkg.cmake 
rmdir /S /Q build
mkdir build && cd build
cmake .. 
start wxWidgets_example.sln
```

vcpkg_root is the root path of your vcpkg installed files.

See [build-system-integration](https://learn.microsoft.com/en-us/vcpkg/concepts/build-system-integration) and [CMake](https://cmake.org/) for more information.

Regards,
Gammasoft

**Comment by slavroman** [comment]
Hello! Thanks for reply!
I will try.
